### PR TITLE
Docs: Developer Quickstart guide

### PR DESCRIPTION
**Pull request by camiinthisthang**
Still needs to be added:
- Creating a wallet with the CLI to sign transactions
- Confirm with Luiz if there's broken compatibility between the latest fuelup and the ts SDK
- Connecting to Fuel testnet
- Rust test isn't passing, checking with Rust team if there was an update to how the test should be written

### CODE REVIEW

**Review by adlerjohn — COMMENTED** [review]
Is this one ready for review?

**Comment by camiinthisthang** [comment]
No not yet @adlerjohn

**Comment by camiinthisthang** [comment]
All done! Thank you sm @luizstacio for your help on the TS stuff, @kayagokalp for your help on the tooling!

**Comment by adlerjohn** [comment]
Closed in favor of #22

**Pull request closed without merging**
