### PR TITLE
Information architecture

### PR DESCRIPTION
**Pull request by camiinthisthang**
- scaffolded out information architecture for the docs with help from Nick

- all links are grayed out in this branch, and content will be added in separate branches. This throws an error when you run the book, but this will be fixed by merging another PR with content so that not all pages are grayd out, this will also be pushed today.

### CODE REVIEW

**Review by SilentCicero — COMMENTED** [review]
@camiinthisthang these are to top priority sections to get done first. Let's take a stab at writing these out.

Priority Things to Document:
- Developer Quickstart
- Why Fuel
- What is Fuel
- Technology
	- Parallel Tx Exec.
	- FuelVM
	- Sway Language

For Developers
	- Links to all the docs and books

**Comment by adlerjohn** [comment]
What's the status of this refactoring @camiinthisthang? Testnet is upcoming and I don't want to have to set this up last minute.

**Comment by camiinthisthang** [comment]
> What's the status of this refactoring @camiinthisthang? Testnet is upcoming and I don't want to have to set this up last minute.

Do you mean refactoring the information architecture? I'm waiting on a few pieces of the docs from various people that I'd like to have by the end of this week, and then the other sections will have a grey'd out link. Let me know if this isn't what you meant :-)

**Comment by adlerjohn** [comment]
Yes, that's what I meant. Could you clean up this PR to grey out the things that are missing, then merge as-is and add more things in follow-up PRs? No need to block this structuring on having all the content ready.

**Comment by camiinthisthang** [comment]
Ok done @adlerjohn - all links are grayed in this PR and content will be added in subsequent PRs, including one going up today, and more going up by end of week

**Review by adlerjohn — COMMENTED** [review]
Could you remove the currently-empty files that were added in this PR? (Or rather, the ones that just have the heading.)

**Comment by camiinthisthang** [comment]
Done @adlerjohn!

**Review by adlerjohn — APPROVED** [review]

**Pull request merged**
